### PR TITLE
feat: Add typedoc generation support

### PR DESCRIPTION
**Pull request by cvarjao**
Initial work to address issue #53.

This introduces support for `typedoc` and leverage `typed-path` to support path-based manipulation provided by lodash

TBD:
Should we commit the generated docs? same main branch? another orphan branch for github pages?

### CODE REVIEW

**Review by mbystedt — COMMENTED** [review]
The docs look pretty swank. No problem with the PR itself. As an artifact, I wouldn't commit them.

I get the feeling that the value of this can be exposed by wrapping this in a user story. The docs need to be put somewhere for some purpose to have value.

**Comment by DerekRoberts** [comment]
@mbystedt "put somewhere for some purpose to have value"?  Other than GitHub?

**Comment by mbystedt** [comment]
@DerekRoberts Maybe? It's for the team to decide. My VS Code already does most of (if not all of ) what this is providing.

**Comment by mbystedt** [comment]
The git ignore should be updated to exclude the docs.

**Comment by DerekRoberts** [comment]
> @DerekRoberts Maybe? It's for the team to decide. My VS Code already does most of (if not all of ) what this is providing.

@mbystedt Sure, let's do that.  My vote is unlikely to go with anything IDE-based, due to lessened portability.  Still, it's all trade-offs.

**Review by mbystedt — DISMISSED** [review]
Thanks for updating the .gitignore.

**Review by mbystedt — APPROVED** [review]

**Pull request merged**
